// Writes src/generated/index.ts: one re-export line per component folder.
//
// WHY IT IS GENERATED. The root barrel is the one file every component folder
// has to touch, and eight people adding components at once is eight conflicts
// in it. Generated from the folder list, nobody edits it: a folder with an
// index.ts is exported, a folder without one is not, and the order is the
// filesystem's rather than an argument.
//
// It runs before tsup, before typecheck and before lint, because all three
// read src/index.ts, which is nothing but a re-export of this file.

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sourceRoot = join(packageRoot, 'src');
const out = join(sourceRoot, 'generated', 'index.ts');

/** Every folder directly under src/ that publishes an index.ts. */
export function componentFolders(root = sourceRoot) {
  return readdirSync(root, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && entry.name !== 'generated')
    .map((entry) => entry.name)
    .filter((name) => {
      try {
        readdirSync(join(root, name));
      } catch {
        return false;
      }
      return readdirSync(join(root, name)).includes('index.ts');
    })
    .sort();
}

export function barrelSource(folders) {
  return [
    '// Generated by scripts/write-barrel.mjs from the folders under src/. Do not edit.',
    ...folders.map((name) => `export * from '../${name}/index.js';`),
    '',
  ].join('\n');
}

function main() {
  const folders = componentFolders();
  const text = barrelSource(folders);
  mkdirSync(dirname(out), { recursive: true });
  let current = null;
  try {
    current = readFileSync(out, 'utf8');
  } catch {
    // Not written yet, which is every clean checkout.
  }
  // Only when it changed: an unconditional write restarts every watcher
  // looking at src/ on each build.
  if (current !== text) writeFileSync(out, text);
  console.warn(`[ui] barrel exports ${folders.length} component folders`);
}

if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) main();
