import StyleDictionary from 'style-dictionary';
import { spawn } from 'node:child_process';
import { watch } from 'node:fs';
import { createHash } from 'node:crypto';
import { readFile, rm, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, relative, resolve, sep } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

// Emit a TypeScript module of flat token constants alongside the CSS layer.
// Consumers get either `import "@crewlethq/tokens/css"` for the variables
// or `import { color } from "@crewlethq/tokens"` for the strongly typed object.
StyleDictionary.registerFormat({
  name: 'crewlet/ts-module',
  format: ({ dictionary }) => {
    const groups = {};
    for (const t of dictionary.allTokens) {
      const [group, ...rest] = t.path;
      groups[group] ??= {};
      let cursor = groups[group];
      for (let i = 0; i < rest.length - 1; i++) {
        cursor[rest[i]] ??= {};
        cursor = cursor[rest[i]];
      }
      cursor[rest[rest.length - 1]] = t.value;
    }
    const lines = ['/* Generated by style-dictionary. Do not edit. */'];
    for (const [name, value] of Object.entries(groups)) {
      lines.push(`export const ${name} = ${JSON.stringify(value, null, 2)} as const;`);
    }
    return lines.join('\n\n') + '\n';
  },
});

const styleDictionaryConfig = {
  source: [resolve(root, 'tokens/**/*.json')],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: resolve(root, 'dist/css/') + '/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          // An alias token (for example font.family.display, which points at
          // font.family.sans) is emitted as var(--font-family-sans) rather
          // than a copy of the resolved value. A custom property holding var()
          // is resolved on the element that declares it and descendants
          // inherit the result, so the alias follows an override of the
          // referenced variable declared on :root (the <html> element) and no
          // other: an override on body, a theme class or any narrower
          // selector has to set the alias as well.
          options: { selector: ':root', outputReferences: true },
        },
      ],
    },
    ts: {
      transformGroup: 'js',
      buildPath: resolve(root, 'src/') + '/',
      files: [
        {
          destination: 'index.ts',
          format: 'crewlet/ts-module',
        },
      ],
    },
  },
};

// Legacy aliases: short, unprefixed variable names that stylesheets written
// before these tokens existed commonly use. Importing
// "@crewlethq/tokens/css/legacy" lets such a stylesheet adopt the tokens without
// rewriting every `var(--accent)` or `var(--bg-primary)` site. New code should
// use the canonical `--color-*` names.
//
// The aliases are declared on the theme selectors as well as on :root. Each
// alias holds a var() reference, which the browser resolves on the element
// that declares it and hands down to descendants as a finished value. Declared
// on :root alone, every alias would keep the :root (dark) palette under
// body.theme-light, because the theme repaints the canonical tokens on body,
// below the element that resolved the alias.
const THEME_SELECTORS = ['body.theme-dark', 'body.theme-light'];

const legacyAliases = `/* Generated by style-dictionary. Legacy aliases mapping short, unprefixed
   variable names to the canonical token namespace. Import this in addition to
   tokens.css when migrating an existing app: import '@crewlethq/tokens/css/legacy';
   New code should reference --color-*, --spacing-*, --font-*, --radius-*,
   --shadow-* directly.

   The aliases are re-declared on the theme classes so they follow a theme
   switch. Override an alias on the element that switches the theme (or a
   descendant of it); an override on :root is replaced inside a themed body. */
${[':root', ...THEME_SELECTORS].join(',\n')} {
  /* Brand */
  --accent: var(--color-brand-primary);
  --primary-blue: var(--color-brand-primary);
  --accent-purple: var(--color-brand-primary);
  --accent-purple-deep: var(--color-brand-accent-deep);
  --accent-pink: var(--color-brand-highlight);
  --accent-slate: var(--color-brand-slate);
  --accent-gradient: var(--color-brand-gradient);

  /* Surface ramp */
  --bg-primary: var(--color-surface-topbar);
  --bg-secondary: var(--color-surface-topbar-lift);
  --bg-tertiary: var(--color-surface-topbar-active);
  --bg-elevated: var(--color-surface-topbar-active);

  /* Text */
  --text-primary: var(--color-text-primary);
  --text-secondary: var(--color-text-secondary);
  --text-tertiary: var(--color-text-tertiary);

  /* Borders */
  --border-color: var(--color-border-default);
  --border-hover: var(--color-border-hover);

  /* Type stacks */
  --font-sans: var(--font-family-sans);
  --font-mono: var(--font-family-mono);
}
`;

// Theme overrides. The base tokens.css emits the dark palette under :root;
// this file repaints the same canonical --color-* slots for body.theme-light
// and body.theme-dark so apps can swap palettes at runtime by toggling a class
// on <body>. The dark theme keeps the base token surfaces but swaps the brand
// primary to white for high-contrast calls to action; the light theme inverts
// the surface and text ramps. Neither touches the brand accent family
// (--color-brand-accent and its hover, active, rgb and soft variants): it is
// the recurring selected, active and focus colour across the components, so
// it stays the one base value whatever the palette, and a component renders
// identically in Storybook and in any application that imports the same two
// files.
//
// Usage:
//   import '@crewlethq/tokens/css';
//   import '@crewlethq/tokens/css/themes';
//   document.body.classList.add('theme-dark'); // or 'theme-light'
const themeOverrides = `/* Generated by style-dictionary. Dark and light theme overrides for the
   canonical --color-* tokens. The base tokens.css already emits the dark
   palette at :root; this file repaints the slots that change between
   themes (the brand accent family is the same in both and is not
   repainted). Import this in addition to tokens.css when an app needs
   runtime theme switching:
       import '@crewlethq/tokens/css';
       import '@crewlethq/tokens/css/themes';
   Apply by toggling body.theme-light or body.theme-dark. */

/* Dark theme. Opaque surface ramp with a white primary action. */
body.theme-dark {
  --color-surface-background: #15171c;
  --color-surface-subtle: #1c1e24;
  --color-surface-muted: #1c1e24;
  --color-surface-elevated: #22252b;
  --color-surface-topbar: #15171c;
  --color-surface-topbar-lift: #1c1e24;
  --color-surface-topbar-active: #22252b;
  --color-text-primary: #fafafa;
  --color-text-secondary: #c9ced8;
  --color-text-tertiary: #8c99ad;
  --color-text-muted: rgba(255, 255, 255, 0.3);
  --color-text-inverse: #09090b;
  --color-brand-primary: #ffffff;
  --color-brand-primary-hover: rgba(255, 255, 255, 0.9);
  --color-brand-primary-active: rgba(255, 255, 255, 0.82);
  --color-text-on-brand: #000000;
  --color-border-default: #3f4145;
  --color-border-hover: #4a4d52;
  --color-border-strong: #3f4145;
  --color-border-strong-hover: #4a4d52;
}

/* Light theme. White surfaces, near-black text and a black primary action. */
body.theme-light {
  --color-surface-background: #ffffff;
  --color-surface-subtle: #f4f4f5;
  --color-surface-muted: #f4f4f5;
  --color-surface-elevated: #e3e3e6;
  --color-surface-topbar: #ffffff;
  --color-surface-topbar-lift: #f4f4f5;
  --color-surface-topbar-active: #e3e3e6;
  --color-text-primary: #09090b;
  --color-text-secondary: #71717a;
  --color-text-tertiary: rgba(25, 25, 28, 0.5);
  --color-text-muted: rgba(0, 0, 0, 0.4);
  --color-text-inverse: #fafafa;
  --color-brand-primary: #000000;
  --color-brand-primary-hover: rgba(0, 0, 0, 0.85);
  --color-brand-primary-active: rgba(0, 0, 0, 0.7);
  --color-text-on-brand: #ffffff;
  --color-border-default: #e4e4e7;
  --color-border-hover: #d4d4d8;
  --color-border-strong: #e4e4e7;
  --color-border-strong-hover: #d4d4d8;
}
`;

// Self-hosted font faces. The woff2 files live in fonts/ (shipped in the
// package tarball beside dist/) with their OFL.txt, so the design system
// renders identically on a closed network and makes no third-party request
// for type. Each family carries the latin and latin-ext subsets Google Fonts
// serves for it; see fonts/README.md for versions and provenance, and
// fonts/SHA256SUMS for the checksum every file is verified against below.
//
// The unicode ranges are the latin and latin-ext ranges from the same Google
// Fonts stylesheet responses the files were downloaded from, so a page that
// renders only basic Latin text downloads a single file per family.
// latin-ext is declared first: the two ranges share
// U+0304, U+0308 and U+0329, and when faces with identical descriptors
// overlap the browser checks the one declared last first, so those combining
// marks resolve from the latin file a Latin page has already downloaded.
const FONT_SUBSETS = [
  {
    name: 'latin-ext',
    unicodeRange:
      'U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF',
  },
  {
    name: 'latin',
    unicodeRange:
      'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
  },
];

// `weight` is the wght axis range recorded in each shipped file's fvar table
// (Inter 100 to 900, JetBrains Mono 100 to 800). Declaring the real range lets
// the browser render every font.weight token inside it from the variable font
// instead of synthesising bold; a narrower range would clamp the heavier
// weights the file can actually draw.
const FONT_FAMILIES = [
  { family: 'Inter', file: 'inter', weight: '100 900' },
  { family: 'JetBrains Mono', file: 'jetbrains-mono', weight: '100 800' },
];

const tokensDir = resolve(root, 'tokens');
const fontsDir = resolve(root, 'fonts');
const cssDir = resolve(root, 'dist/css');
const fontsUrlBase = relative(cssDir, fontsDir).split(sep).join('/');

// Reads fonts/SHA256SUMS (the `shasum -a 256` output format) into a map of
// file name to checksum.
async function fontChecksums() {
  const checksums = new Map();
  const text = await readFile(resolve(fontsDir, 'SHA256SUMS'), 'utf8');
  for (const line of text.split('\n').filter(Boolean)) {
    const match = /^([0-9a-f]{64}) [ *](\S+)$/.exec(line);
    if (!match) throw new Error(`fonts/SHA256SUMS: malformed line "${line}"`);
    checksums.set(match[2], match[1]);
  }
  return checksums;
}

async function fontFaceRules() {
  const checksums = await fontChecksums();
  const referenced = new Set();
  const rules = [];
  for (const { family, file, weight } of FONT_FAMILIES) {
    for (const { name, unicodeRange } of FONT_SUBSETS) {
      const fileName = `${file}-${name}.woff2`;
      referenced.add(fileName);
      // Fail the build rather than publish a stylesheet that points at a
      // missing file (a silent fallback font), or a file whose bytes no
      // longer match the provenance recorded for it.
      const expected = checksums.get(fileName);
      if (expected === undefined) {
        throw new Error(`fonts/SHA256SUMS has no checksum for ${fileName}; see "Replacing a file" in fonts/README.md`);
      }
      const actual = createHash('sha256').update(await readFile(resolve(fontsDir, fileName))).digest('hex');
      if (actual !== expected) {
        throw new Error(
          `fonts/${fileName} has SHA-256 ${actual}, but fonts/SHA256SUMS records ${expected}; see "Replacing a file" in fonts/README.md`,
        );
      }
      rules.push(`@font-face {
  font-family: '${family}';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url('${fontsUrlBase}/${fileName}') format('woff2');
  unicode-range: ${unicodeRange};
}`);
    }
  }
  const stale = [...checksums.keys()].filter((fileName) => !referenced.has(fileName));
  if (stale.length > 0) {
    throw new Error(`fonts/SHA256SUMS lists files no @font-face rule uses: ${stale.join(', ')}`);
  }
  return rules.join('\n\n');
}

// Font face loader. Ships separately from tokens.css so consumers who already
// load fonts at the app shell can opt out. It references local files only.
const fontFacesHeader = `/* Generated by style-dictionary. Self-hosted faces for the type families
   referenced by --font-family-sans, --font-family-display (an alias of sans)
   and --font-family-mono. Import this in addition to tokens.css when uilet
   should own font loading:
       import '@crewlethq/tokens/css';
       import '@crewlethq/tokens/css/fonts';
   Apps that already load these fonts at the shell can skip this file.

   Inter and JetBrains Mono are licensed under the SIL Open Font License 1.1.
   See fonts/OFL.txt in this package. */
`;

// Material Symbols Outlined loader, kept out of fonts.css on purpose: it is
// the one stylesheet in this package that requests a third-party host, so an
// application has to opt in to it explicitly. The @crewlethq/ui components
// render their glyphs as ligatures inside
// <span class="material-symbols-outlined">, and the Google Fonts response
// defines both the face and that class.
const materialSymbols = `/* Generated by style-dictionary. Loads the Material Symbols Outlined icon
   font that @crewlethq/ui components render through
   <span class="material-symbols-outlined">. Import it when the app renders
   those components and does not load the icon font itself:
       import '@crewlethq/tokens/css/material-symbols';

   This stylesheet requests fonts.googleapis.com, and the browser then
   downloads the font from fonts.gstatic.com. Material Symbols is published
   by Google under the Apache License 2.0
   (https://github.com/google/material-design-icons). No part of it is
   redistributed in this package. */

@import url('https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap');
`;

async function build() {
  // The constructor's implicit init runs detached, so a malformed token file
  // would surface as an unhandled rejection that no caller can catch (and
  // would crash watch mode). Initialising explicitly routes that error
  // through this function's promise instead.
  const sd = new StyleDictionary(styleDictionaryConfig, { init: false });
  await sd.init();
  await sd.cleanAllPlatforms();
  await sd.buildAllPlatforms();

  await writeFile(resolve(cssDir, 'legacy.css'), legacyAliases);
  await writeFile(resolve(cssDir, 'themes.css'), themeOverrides);
  await writeFile(resolve(cssDir, 'fonts.css'), `${fontFacesHeader}\n${await fontFaceRules()}\n`);
  await writeFile(resolve(cssDir, 'material-symbols.css'), materialSymbols);

  console.warn('[tokens] built CSS, legacy aliases, theme overrides, font faces, Material Symbols loader, and TS module');
}

if (process.argv.includes('--watch')) {
  await startWatching();
} else {
  // A one-shot build starts from an empty dist/. Style Dictionary only cleans
  // the files it generates itself, so anything else (the tsc output, or a
  // stylesheet a later change stopped generating) would otherwise survive
  // from an earlier build and be packed into the next tarball.
  await rm(resolve(root, 'dist'), { recursive: true, force: true });
  await build();
}

// Watch mode for `npm run dev`. The one-shot build above only regenerates the
// CSS and src/index.ts; the typed module in dist/ comes from tsc, so watch
// mode also runs tsc in watch mode against the regenerated source. Token and
// font changes trigger a rebuild. A failed build (for example a JSON syntax
// error mid-edit, including at startup) is reported and the watcher keeps
// running, so the next save recovers without restarting the dev loop.
async function startWatching() {
  // Editors often emit several events for one save; a short quiet period
  // folds them into a single rebuild without a noticeable delay.
  const REBUILD_DEBOUNCE_MS = 100;

  let timer;
  let running = false;
  let pending = false;

  const rebuild = async () => {
    if (running) {
      pending = true;
      return;
    }
    running = true;
    try {
      await build();
    } catch (error) {
      console.error('[tokens] rebuild failed:', error);
    } finally {
      running = false;
    }
    if (pending) {
      pending = false;
      await rebuild();
    }
  };

  const schedule = () => {
    clearTimeout(timer);
    timer = setTimeout(rebuild, REBUILD_DEBOUNCE_MS);
  };

  // Generate src/index.ts before tsc starts, so its first pass compiles the
  // current tokens instead of reporting a missing module.
  await rebuild();

  const requireFromScript = createRequire(import.meta.url);
  const tsc = spawn(
    process.execPath,
    [requireFromScript.resolve('typescript/bin/tsc'), '-p', 'tsconfig.json', '--watch', '--preserveWatchOutput'],
    { cwd: root, stdio: 'inherit' },
  );

  const watchers = [tokensDir, fontsDir].map((dir) => watch(dir, { recursive: true }, schedule));

  const stop = (exitCode) => {
    clearTimeout(timer);
    for (const watcher of watchers) watcher.close();
    if (tsc.exitCode === null) tsc.kill();
    process.exit(exitCode);
  };

  process.on('SIGINT', () => stop(0));
  process.on('SIGTERM', () => stop(0));
  // The tsc child must never outlive this process, including when it ends on
  // an uncaught exception rather than through stop().
  process.on('exit', () => {
    if (tsc.exitCode === null) tsc.kill();
  });
  tsc.on('exit', (code, signal) => {
    // An interrupt from the terminal reaches tsc as well; that is a normal
    // shutdown, not a failure.
    if (signal === 'SIGINT' || signal === 'SIGTERM') {
      stop(0);
      return;
    }
    // Without tsc the dev loop would silently stop updating dist/index.js,
    // so losing it ends watch mode rather than leaving a half-working watcher.
    console.error(`[tokens] tsc watcher exited with code ${code}; stopping watch mode`);
    stop(code || 1);
  });

  console.warn('[tokens] watching tokens/ and fonts/ for changes');
}
