import { readdir, readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import { dirname, resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { transform } from '@svgr/core';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const svgDir = resolve(root, 'svg');
const outDir = resolve(root, 'src/generated');

const toPascal = (name) =>
  name
    .replace(/\.svg$/, '')
    .split(/[-_\s]+/)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');

// Every icon renders inline, so all of them share the document's id space,
// and `url(#id)` resolves to the first element with that id on the page.
// preset-default minifies ids (a gradient named hierGrad becomes `a` in every
// file), so without a per-file prefix each illustration after the first on a
// page painted with the first one's gradient. prefixIds runs after the
// minification and namespaces each file's ids with its own name.
const svgrConfigFor = (iconName) => ({
  plugins: ['@svgr/plugin-svgo', '@svgr/plugin-jsx'],
  jsxRuntime: 'automatic',
  typescript: true,
  expandProps: 'end',
  svgProps: {
    width: '1em',
    height: '1em',
    fill: 'currentColor',
    'aria-hidden': 'true',
    focusable: 'false',
  },
  prettier: false,
  svgoConfig: {
    plugins: [
      {
        name: 'preset-default',
        params: { overrides: { removeViewBox: false } },
      },
      'removeDimensions',
      { name: 'prefixIds', params: { prefix: `crewlet-icon-${iconName}`, delim: '__' } },
    ],
  },
});

async function build() {
  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  // Sorted, because readdir returns directory order, which differs between
  // file systems, and ICON_NAMES and the generated index must come out the
  // same on every machine that builds them.
  const files = (await readdir(svgDir)).filter((f) => f.endsWith('.svg')).sort();

  if (files.length === 0) {
    // Always emit something so the package builds even when svg/ is empty
    await writeFile(
      resolve(outDir, 'index.ts'),
      '// Generated by build.mjs. Drop SVGs into svg/ and rerun build.\nexport const ICON_NAMES = [] as const;\nexport type IconName = (typeof ICON_NAMES)[number];\n',
    );
    return;
  }

  const exports = [];
  const names = [];

  for (const file of files) {
    const componentName = toPascal(basename(file));
    const svg = await readFile(resolve(svgDir, file), 'utf8');
    const code = await transform(svg, svgrConfigFor(basename(file, '.svg')), { componentName });
    await writeFile(resolve(outDir, `${componentName}.tsx`), code);
    exports.push(`export { default as ${componentName} } from './${componentName}';`);
    names.push(componentName);
  }

  const indexBody = [
    '// Generated by build.mjs. Do not edit.',
    ...exports,
    '',
    `export const ICON_NAMES = [${names.map((n) => `'${n}'`).join(', ')}] as const;`,
    'export type IconName = (typeof ICON_NAMES)[number];',
    '',
  ].join('\n');

  await writeFile(resolve(outDir, 'index.ts'), indexBody);
  console.warn(`[icons] generated ${names.length} icon component(s)`);
}

await build();
