import { readdir, readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import { dirname, resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { transform } from '@svgr/core';

import { FILLABLE, componentName, readGlyphs } from './glyphs.mjs';
import { extent, markPaths } from './mark.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const svgDir = resolve(root, 'svg');
const vendorDir = resolve(svgDir, 'vendor');
const outDir = resolve(root, 'src/generated');

const toPascal = (name) =>
  name
    .replace(/\.svg$/, '')
    .split(/[-_\s]+/)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');

// Every icon renders inline, so all of them share the document's id space,
// and `url(#id)` resolves to the first element with that id on the page.
// preset-default minifies ids (a gradient named hierGrad becomes `a` in every
// file), so without a per-file prefix each illustration after the first on a
// page painted with the first one's gradient. prefixIds runs after the
// minification and namespaces each file's ids with its own name.
const svgrConfigFor = (iconName, source, idPrefix) => ({
  plugins: ['@svgr/plugin-svgo', '@svgr/plugin-jsx'],
  jsxRuntime: 'automatic',
  typescript: true,
  expandProps: 'end',
  svgProps: {
    width: '1em',
    height: '1em',
    // Only where the source root declares no fill of its own. Forcing
    // currentColor here filled every stroke illustration in the package: the
    // eight agent poses and the three feature illustrations all open with
    // `fill="none"`, and overriding that painted the inside of every closed
    // path in the text colour, which is not what any of them draw.
    ...(declaresFill(source) ? {} : { fill: 'currentColor' }),
    'aria-hidden': 'true',
    focusable: 'false',
  },
  prettier: false,
  svgoConfig: {
    plugins: [
      {
        name: 'preset-default',
        params: { overrides: { removeViewBox: false } },
      },
      'removeDimensions',
      { name: 'prefixIds', params: { prefix: `${idPrefix}-${iconName}`, delim: '__' } },
    ],
  },
});

// Whether the root <svg> element carries a fill attribute of its own.
function declaresFill(source) {
  const openingTag = /<svg\b[^>]*>/.exec(source);
  return openingTag !== null && /\sfill\s*=/.test(openingTag[0]);
}

async function compileDirectory(directory, { into, idPrefix, kind }) {
  // Sorted, because readdir returns directory order, which differs between
  // file systems, and the generated names and index must come out the same on
  // every machine that builds them.
  const files = (await readdir(directory, { withFileTypes: true }))
    .filter((entry) => entry.isFile() && entry.name.endsWith('.svg'))
    .map((entry) => entry.name)
    .sort();
  const names = [];
  for (const file of files) {
    const name = toPascal(basename(file));
    const svg = await readFile(resolve(directory, file), 'utf8');
    const code = await transform(svg, svgrConfigFor(basename(file, '.svg'), svg, idPrefix), { componentName: name });
    await writeFile(resolve(into, `${name}.tsx`), code);
    names.push(name);
  }
  if (names.length === 0) throw new Error(`${kind}: no SVG files in ${directory}`);
  return names;
}

// The illustrations: the brand artwork, the feature illustrations and the
// agent poses, each its own component and each also reachable by name through
// <Icon>.
async function buildIllustrations() {
  const names = await compileDirectory(svgDir, { into: outDir, idPrefix: 'crewlet-icon', kind: 'illustrations' });
  const body = [
    '// Generated by build.mjs. Do not edit.',
    ...names.map((name) => `export { default as ${name} } from './${name}.js';`),
    '',
    `export const ICON_NAMES = [${names.map((name) => JSON.stringify(name)).join(', ')}] as const;`,
    'export type IconName = (typeof ICON_NAMES)[number];',
    '',
  ].join('\n');
  await writeFile(resolve(outDir, 'index.ts'), body);

  /*
   * The by-name registry as an explicit object literal, not a namespace
   * import. `import * as Generated` compiles to a call at module scope that
   * names every illustration, which nothing can prove is safe to drop, so
   * every consumer of this package carried all 558 KB whether or not it used
   * <Icon>. One const carries the same map and disappears with <Icon> when
   * nobody imports it (measured: 515 KB against 2 KB).
   */
  const registry = [
    '// Generated by build.mjs. Do not edit.',
    "import type { ComponentType, SVGProps } from 'react';",
    ...names.map((name) => `import ${name} from './${name}.js';`),
    "import type { IconName } from './index.js';",
    '',
    'export const ICONS: Record<IconName, ComponentType<SVGProps<SVGSVGElement>>> = {',
    ...names.map((name) => `  ${name},`),
    '};',
    '',
  ].join('\n');
  await writeFile(resolve(outDir, 'registry.ts'), registry);
  return names.length;
}

// The third-party marks. Their own directory, and their own generated index,
// because they are not part of the signature set: a vendor mark is drawn by
// <VendorMark vendor="slack" />, which is the one surface that carries the
// rules about somebody else's colours, and reaching one through <Icon> would
// be a second way to draw the same thing.
async function buildVendorMarks() {
  const into = resolve(outDir, 'vendors');
  await mkdir(into, { recursive: true });
  const names = await compileDirectory(vendorDir, { into, idPrefix: 'crewlet-vendor', kind: 'vendor marks' });
  const body = [
    '// Generated by build.mjs. Do not edit.',
    ...names.map((name) => `export { default as ${name} } from './${name}.js';`),
    '',
  ].join('\n');
  await writeFile(resolve(into, 'index.ts'), body);
  return names.length;
}

// The Lucide glyphs. Written out rather than compiled by SVGR: each vendored
// file is a list of geometry elements on the 24 grid (scripts/glyphs.mjs
// refuses anything else), and running the optimiser over it would ship
// drawings that no longer match the checksums the provenance rests on. The
// elements are copied across attribute for attribute; the stroke, the caps and
// the joins are the frame's, in src/Glyph.tsx, so every glyph draws at one
// weight whatever upstream's files say.
async function buildGlyphs() {
  const into = resolve(outDir, 'glyphs');
  await mkdir(into, { recursive: true });
  const glyphs = await readGlyphs();
  const fillable = new Set(FILLABLE);
  const exports = [];
  const components = new Map();
  for (const [name, elements] of glyphs) {
    const component = componentName(name);
    // Two upstream names can only collide here if one of them is an alias the
    // vendoring script would have refused, but a collision is the one failure
    // that would silently export the wrong drawing under a right name.
    if (components.has(component)) {
      throw new Error(`glyphs/${name}.svg and glyphs/${components.get(component)}.svg both compile to ${component}`);
    }
    components.set(component, name);
    const props = fillable.has(name) ? 'FillableGlyphProps' : 'GlyphProps';
    /*
     * `fillable` is written AFTER the caller's props, so whether a glyph can be
     * filled is the drawing's answer and never the caller's: the types keep
     * `filled` off every other glyph, and this keeps it off for a caller the
     * types do not reach, where an open stroke would fill into a blob.
     */
    /*
     * A function DECLARATION, and no displayName assignment. Both matter:
     * `X.displayName = 'X'` is a statement at module scope, and neither esbuild
     * nor a consumer's bundler can prove it is safe to drop, so one of them
     * pins every glyph in the file and importing XGlyph alone carried all of
     * them (measured on the Material set: 67 KB against 1 KB). A declaration's
     * own name is what React DevTools reads anyway.
     */
    const body = [
      '// Generated by build.mjs from glyphs/. Do not edit.',
      `import type { ${props} } from '../../Glyph.js';`,
      "import { Glyph } from '../../Glyph.js';",
      '',
      `export default function ${component}(props: ${props}) {`,
      '  return (',
      `    <Glyph {...props} fillable={${fillable.has(name)}}>`,
      ...elements.map(
        ({ tag, attrs }) =>
          `      <${tag} ${Object.entries(attrs)
            .map(([key, value]) => `${key}={${JSON.stringify(value)}}`)
            .join(' ')} />`,
      ),
      '    </Glyph>',
      '  );',
      '}',
      '',
    ].join('\n');
    await writeFile(resolve(into, `${component}.tsx`), body);
    exports.push({ name, component });
  }
  const index = [
    '// Generated by build.mjs from glyphs/. Do not edit.',
    ...exports.map(({ component }) => `export { default as ${component} } from './${component}.js';`),
    '',
    `export const GLYPH_NAMES = [${exports.map(({ name }) => JSON.stringify(name)).join(', ')}] as const;`,
    'export type GlyphName = (typeof GLYPH_NAMES)[number];',
    '',
    `export const FILLABLE = [${FILLABLE.map((name) => JSON.stringify(name)).join(', ')}] as const satisfies readonly GlyphName[];`,
    'export type FillableGlyphName = (typeof FILLABLE)[number];',
    '',
  ].join('\n');
  await writeFile(resolve(into, 'index.ts'), index);

  // The registry is generated beside the components rather than written by
  // hand because it has to name every one of them, and a hand-written map is
  // where a glyph added to glyphs/ quietly goes missing. `as const` keeps each
  // entry's own component type, so `glyphByName('star')` takes `filled` and
  // `glyphByName('x')` does not.
  const registry = [
    '// Generated by build.mjs from glyphs/. Do not edit.',
    "import type { ComponentType } from 'react';",
    "import type { GlyphProps } from '../../Glyph.js';",
    ...exports.map(({ component }) => `import ${component} from './${component}.js';`),
    "import type { GlyphName } from './index.js';",
    '',
    'export const GLYPHS = {',
    ...exports.map(({ name, component }) => `  ${JSON.stringify(name)}: ${component},`),
    '} as const satisfies Record<GlyphName, ComponentType<GlyphProps>>;',
    '',
  ].join('\n');
  await writeFile(resolve(into, 'registry.ts'), registry);
  return exports.length;
}

// The mark's own paths and the box they occupy, for the characters. The
// original Crewlet character IS the mark, so it is drawn from this file rather
// than from a copy of its paths, and its frame is measured from the drawing
// rather than remembered as four numbers.
async function buildMark() {
  const paths = markPaths(await readFile(resolve(svgDir, 'crewlet-icon.svg'), 'utf8'));
  if (paths.length !== 3) throw new Error(`svg/crewlet-icon.svg has ${paths.length} paths, and the characters draw three`);
  const box = extent(paths);
  const body = [
    '// Generated by build.mjs from svg/crewlet-icon.svg. Do not edit.',
    '',
    '/** The mark\'s three paths (its keyline, its body and its visor) and the box they occupy, in its own units. */',
    'export const CREWLET_MARK = {',
    `  paths: [${paths.map((d) => JSON.stringify(d)).join(', ')}] as const,`,
    `  box: { left: ${box.left}, top: ${box.top}, right: ${box.right}, bottom: ${box.bottom} },`,
    '} as const;',
    '',
  ].join('\n');
  await writeFile(resolve(outDir, 'crewletMark.ts'), body);
}

async function build() {
  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  const illustrations = await buildIllustrations();
  const vendors = await buildVendorMarks();
  const glyphs = await buildGlyphs();
  await buildMark();
  console.warn(`[icons] generated ${illustrations} illustration(s), ${vendors} vendor mark(s) and ${glyphs} glyph(s)`);
}

await build();
