import { readdir, readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import { dirname, resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { transform } from '@svgr/core';

import { componentName, readGlyphs } from './symbols.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const svgDir = resolve(root, 'svg');
const vendorDir = resolve(svgDir, 'vendor');
const outDir = resolve(root, 'src/generated');

const toPascal = (name) =>
  name
    .replace(/\.svg$/, '')
    .split(/[-_\s]+/)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');

// Every icon renders inline, so all of them share the document's id space,
// and `url(#id)` resolves to the first element with that id on the page.
// preset-default minifies ids (a gradient named hierGrad becomes `a` in every
// file), so without a per-file prefix each illustration after the first on a
// page painted with the first one's gradient. prefixIds runs after the
// minification and namespaces each file's ids with its own name.
const svgrConfigFor = (iconName, source, idPrefix) => ({
  plugins: ['@svgr/plugin-svgo', '@svgr/plugin-jsx'],
  jsxRuntime: 'automatic',
  typescript: true,
  expandProps: 'end',
  svgProps: {
    width: '1em',
    height: '1em',
    // Only where the source root declares no fill of its own. Forcing
    // currentColor here filled every stroke illustration in the package: the
    // eight agent poses and the three feature illustrations all open with
    // `fill="none"`, and overriding that painted the inside of every closed
    // path in the text colour, which is not what any of them draw.
    ...(declaresFill(source) ? {} : { fill: 'currentColor' }),
    'aria-hidden': 'true',
    focusable: 'false',
  },
  prettier: false,
  svgoConfig: {
    plugins: [
      {
        name: 'preset-default',
        params: { overrides: { removeViewBox: false } },
      },
      'removeDimensions',
      { name: 'prefixIds', params: { prefix: `${idPrefix}-${iconName}`, delim: '__' } },
    ],
  },
});

// Whether the root <svg> element carries a fill attribute of its own.
function declaresFill(source) {
  const openingTag = /<svg\b[^>]*>/.exec(source);
  return openingTag !== null && /\sfill\s*=/.test(openingTag[0]);
}

async function compileDirectory(directory, { into, idPrefix, kind }) {
  // Sorted, because readdir returns directory order, which differs between
  // file systems, and the generated names and index must come out the same on
  // every machine that builds them.
  const files = (await readdir(directory, { withFileTypes: true }))
    .filter((entry) => entry.isFile() && entry.name.endsWith('.svg'))
    .map((entry) => entry.name)
    .sort();
  const names = [];
  for (const file of files) {
    const name = toPascal(basename(file));
    const svg = await readFile(resolve(directory, file), 'utf8');
    const code = await transform(svg, svgrConfigFor(basename(file, '.svg'), svg, idPrefix), { componentName: name });
    await writeFile(resolve(into, `${name}.tsx`), code);
    names.push(name);
  }
  if (names.length === 0) throw new Error(`${kind}: no SVG files in ${directory}`);
  return names;
}

// The illustrations: the brand artwork, the feature illustrations and the
// agent poses, each its own component and each also reachable by name through
// <Icon>.
async function buildIllustrations() {
  const names = await compileDirectory(svgDir, { into: outDir, idPrefix: 'crewlet-icon', kind: 'illustrations' });
  const body = [
    '// Generated by build.mjs. Do not edit.',
    ...names.map((name) => `export { default as ${name} } from './${name}.js';`),
    '',
    `export const ICON_NAMES = [${names.map((name) => JSON.stringify(name)).join(', ')}] as const;`,
    'export type IconName = (typeof ICON_NAMES)[number];',
    '',
  ].join('\n');
  await writeFile(resolve(outDir, 'index.ts'), body);

  /*
   * The by-name registry as an explicit object literal, not a namespace
   * import. `import * as Generated` compiles to a call at module scope that
   * names every illustration, which nothing can prove is safe to drop, so
   * every consumer of this package carried all 558 KB whether or not it used
   * <Icon>. One const carries the same map and disappears with <Icon> when
   * nobody imports it (measured: 515 KB against 2 KB).
   */
  const registry = [
    '// Generated by build.mjs. Do not edit.',
    "import type { ComponentType, SVGProps } from 'react';",
    ...names.map((name) => `import ${name} from './${name}.js';`),
    "import type { IconName } from './index.js';",
    '',
    'export const ICONS: Record<IconName, ComponentType<SVGProps<SVGSVGElement>>> = {',
    ...names.map((name) => `  ${name},`),
    '};',
    '',
  ].join('\n');
  await writeFile(resolve(outDir, 'registry.ts'), registry);
  return names.length;
}

// The third-party marks. Their own directory, and their own generated index,
// because they are not part of the signature set: a vendor mark is drawn by
// <VendorMark vendor="slack" />, which is the one surface that carries the
// rules about somebody else's colours, and reaching one through <Icon> would
// be a second way to draw the same thing.
async function buildVendorMarks() {
  const into = resolve(outDir, 'vendors');
  await mkdir(into, { recursive: true });
  const names = await compileDirectory(vendorDir, { into, idPrefix: 'crewlet-vendor', kind: 'vendor marks' });
  const body = [
    '// Generated by build.mjs. Do not edit.',
    ...names.map((name) => `export { default as ${name} } from './${name}.js';`),
    '',
  ].join('\n');
  await writeFile(resolve(into, 'index.ts'), body);
  return names.length;
}

// The Material Symbols glyphs. Written out rather than compiled by SVGR: each
// vendored file is one path on one viewBox (scripts/symbols.mjs refuses
// anything else), and running the optimiser over it would ship path data that
// no longer matches the checksum the provenance rests on. Both optical sizes
// travel in one component, so `CloseGlyph` is the whole of close and a bundler
// keeps or drops it in one piece.
async function buildGlyphs() {
  const into = resolve(outDir, 'glyphs');
  await mkdir(into, { recursive: true });
  const glyphs = await readGlyphs();
  const exports = [];
  for (const [name, drawing] of glyphs) {
    const component = componentName(name);
    /*
     * A function DECLARATION, and no displayName assignment. Both matter:
     * `X.displayName = 'X'` is a statement at module scope, and neither esbuild
     * nor a consumer's bundler can prove it is safe to drop, so one of them
     * pins every glyph in the file and importing CloseGlyph alone carried all
     * 98 (measured: 67 KB against 1 KB). A declaration's own name is what React
     * DevTools reads anyway.
     */
    const body = [
      '// Generated by build.mjs from symbols/. Do not edit.',
      "import type { GlyphDrawing, GlyphProps } from '../../Glyph.js';",
      "import { Glyph } from '../../Glyph.js';",
      '',
      'const drawing: GlyphDrawing = {',
      `  20: ${JSON.stringify(drawing[20])},`,
      `  24: ${JSON.stringify(drawing[24])},`,
      '};',
      '',
      `export default function ${component}(props: GlyphProps) {`,
      '  return <Glyph {...props} drawing={drawing} />;',
      '}',
      '',
    ].join('\n');
    await writeFile(resolve(into, `${component}.tsx`), body);
    exports.push({ name, component });
  }
  const index = [
    '// Generated by build.mjs from symbols/. Do not edit.',
    ...exports.map(({ component }) => `export { default as ${component} } from './${component}.js';`),
    '',
    `export const GLYPH_NAMES = [${exports.map(({ name }) => JSON.stringify(name)).join(', ')}] as const;`,
    'export type GlyphName = (typeof GLYPH_NAMES)[number];',
    '',
  ].join('\n');
  await writeFile(resolve(into, 'index.ts'), index);

  // The registry is generated beside the components rather than written by
  // hand because it has to name every one of them, and a hand-written map is
  // where a glyph added to symbols/ quietly goes missing.
  const registry = [
    '// Generated by build.mjs from symbols/. Do not edit.',
    "import type { ComponentType } from 'react';",
    "import type { GlyphProps } from '../../Glyph.js';",
    ...exports.map(({ component }) => `import ${component} from './${component}.js';`),
    "import type { GlyphName } from './index.js';",
    '',
    'export const GLYPHS: Record<GlyphName, ComponentType<GlyphProps>> = {',
    ...exports.map(({ name, component }) => `  ${JSON.stringify(name)}: ${component},`),
    '};',
    '',
  ].join('\n');
  await writeFile(resolve(into, 'registry.ts'), registry);
  return exports.length;
}

async function build() {
  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  const illustrations = await buildIllustrations();
  const vendors = await buildVendorMarks();
  const glyphs = await buildGlyphs();
  console.warn(`[icons] generated ${illustrations} illustration(s), ${vendors} vendor mark(s) and ${glyphs} glyph(s)`);
}

await build();
